### ISSUE TITLE
Port 0.7.0 changes back from main circe repository

### ISSUE THREAD

**Issue by travisbrown** [circe/circe-jackson#1]
When I split circe-jackson into its own project I started with the current circe master branch, but had to change some things in order to be able to publish an 0.6.x version depending on circe 0.6.1.

We'll need to update this new repository with the post-0.6.x changes from the main project. This should be relatively straightforward but not just a matter of copy-paste.

**Comment by n4to4** [comment]
I will give it a try

**Comment by travisbrown** [comment]
@n4to4 :+1:, thanks!

**Comment by travisbrown** [comment]
Done in #5.
