### ISSUE TITLE
Jackson 2.10 (jackson210)

### ISSUE THREAD

**Issue by etspaceman** [circe/circe-jackson#129]
The 2.10.X series for Jackson was released in September, 2019. `circe-jackson` should be updated to support this series.

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10

**Comment by travisbrown** [comment]
:+1:, I've been meaning to do this, and might be able to get to it this week. If someone wants to open a PR I'd be happy to review and publish a new release (adding 2.10 should be fairly mechanical copy-paste).

**Comment by travisbrown** [comment]
Fixed in #135. Will publish soon.

**Comment by frankgrimes97** [comment]
@travisbrown Any plans to release a Scala-2.11 compatible version of this? (Would require a `circe-jackson-0.11.2` release?

**Comment by travisbrown** [comment]
@frankgrimes97 If someone prepares a backport branch I'd be happy to publish it.
