### ISSUE TITLE
Artifacts for circe-jackson211 and circe-jackson212 not available in Maven Central

### ISSUE THREAD

**Issue by ane** [circe/circe-jackson#255]
https://repo1.maven.org/maven2/io/circe/ lists only circe-jackson up to circe-jackson210. Seems versions for 2.11 and 2.12 have not been published to Sonatype Central?

**Comment by travisbrown** [comment]
Jackson 2.11 and 2.12 were released since the last release of this project, and I never got around to publishing artifacts for them. This is now done in [0.14.0](https://github.com/circe/circe-jackson/releases/tag/v0.14.0).
