### ISSUE TITLE
Could we do a release?

### ISSUE THREAD

**Issue by tlazaro** [circe/circe-jackson#377]
Hi everyone,

I have a project using Jackson 2.13.4 and would like to use `circe-jackson213`. It seems it exists: https://github.com/circe/circe-jackson/pull/307, but a release hasn't been done since, so the module is not published on Maven.

Would it be possible to do a release?

Thanks!

**Comment by zmccoy** [comment]
Hi @tlazaro if we can get the build onto https://github.com/circe/sbt-circe-org like what was done on https://github.com/circe/circe-config/pull/361 and circe-fs2 that would help us get a release out with mima checks and the release easily.  @zarthross and I will help shepherd that through.
